-- Product owns BIN; Card Type owns default limit profile
-- Oracle-safe: add columns if missing

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCT ADD BIN NUMBER(10)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD DEFAULT_LIMIT_PROFILE_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- Backfill product BIN from an existing card type BIN (first non-null per product)
MERGE INTO CARD_PRODUCT p
USING (
  SELECT PRODUCT_CODE, MAX(BIN) AS BIN
  FROM CARD_TYPE
  WHERE BIN IS NOT NULL AND PRODUCT_CODE IS NOT NULL
  GROUP BY PRODUCT_CODE
) t
ON (p.PRODUCT_CODE = t.PRODUCT_CODE)
WHEN MATCHED THEN UPDATE SET p.BIN = t.BIN
WHERE p.BIN IS NULL;
/

-- Optional FK (ignore if already exists / data mismatch)
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD CONSTRAINT FK_CARD_TYPE_DEFAULT_LIMIT
    FOREIGN KEY (DEFAULT_LIMIT_PROFILE_ID) REFERENCES LIMIT_PROFILE(ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/
